import type { Metadata } from "next";
import { PT_Serif_Caption } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../theme/ThemeProvider";

const ptSerifCaption = PT_Serif_Caption({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-pt-serif-caption",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ptSerifCaption.variable}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
